definitions:
  User:
    type: 'object'
    required:
      - 'first_name'
      - 'last_name'
      - 'email'
      - 'password'
    properties:
      email:
        type: 'string'
        example: 'user@email.com'
      first_name:
        type: 'string'
        example: 'John'
      last_name:
        type: 'string'
        example: 'Doe'
      password:
        type: 'string'
        example: 'password123'
    xml:
      name: 'User'
  UserCredentials:
    type: 'object'
    required:
      - 'email'
      - 'password'
    properties:
      email:
        type: 'string'
        example: 'user@email.com'
      password:
        type: 'string'
        example: 'password123'
    xml:
      name: 'UserCredentials'
