tags:
  - name: 'Checks'
    description: 'Endpoints related to checking API status'
  - name: 'User'
    description: 'Endpoints related to users'
  - name: 'Auth'
    description: 'Endpoints related to authentication'
