components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          formart: int64
        first_name:
          type: string
        last_name:
          type: string
        password:
          type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
