name: CI Step

on:
  pull_request:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cp env files
      run: cp .env.example .env
    - name: Setup container
      run: docker-compose -f docker-compose.test.yml build
    - name: Start container
      run: docker-compose -f docker-compose.test.yml up -d
    - name: Run Jest tests
      run: docker exec -it node-express-starter_api_1 yarn test
